apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-api
  namespace: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app-api
  template:
    metadata:
      labels:
        app: example-app-api
    spec:
      containers:
        - name: example-app-api
          image: fastapi-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: example-app-config
            - secretRef:
                name: example-app-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10